Bookstore: styling
jlcarrascof/bookstore-cms pull request #5
Opened 2023-08-26 02:58 UTC by jlcarrascof

In this pull request, I implemented the following;

Added **missing JSX elements to your project** (without adding extra functionality)
Added **a circular progress component**
Made **sure the final design of the bookstore project should match** [Zeplin's design](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378)

2023-08-26 03:27 UTC, Efiamotu-1 requested changes
Hi @jlcarrascof , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 03:27 UTC, Efiamotu-1 commented on src/index.css
- Great job achieving the project's design 👍 ✨ 
- [ ] From the project design shown below you can see that the `Books` navigation has a slightly bolder font weight than the categories because that is the currently active page on the screen, I want to kindly suggest you adopt this same styling in your project 👍  
- project design
![fb](https://github.com/jlcarrascof/bookstore-cms/assets/89055502/ecb9f30e-df1f-4081-b4cb-dcd66d1c3645)
- your design
![fb-1](https://github.com/jlcarrascof/bookstore-cms/assets/89055502/343ef62c-baa4-4132-a909-51486d45bfb1)

2023-08-26 05:35 UTC, jlcarrascof commented on src/index.css
Copied, dear reviewer **@Efiamotu-1** 

The **active link**, and the **icon on the right side**.

2023-08-26 14:10 UTC, jlcarrascof commented on src/index.css
![UPDATES-REVIEWER](https://github.com/jlcarrascof/bookstore-cms/assets/86327867/09073eac-e48d-43b0-b8d4-ca587571b081)


Dear reviewer, **here the updates requested**.

PS: Please read the notes on the next pull request **about my Readme file**.

2023-08-26 14:41 UTC, Alusp approved these changes
Hi @jlcarrascof, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats](https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif)


## Highlights
✔️ Implemented the change requested to ensure the design matches the design given.

## Optional suggestions

- [OPTIONAL]  Please ensure that your categories section has a dropdown list and its icon. 
Kindly follow the instructions on the project requirement to complete this milestone. according to project requirements, Your final design should match zeplin's design (this includes all elements + the same styling)
You may use the CSS rules detailed in Zeplin to style the website.

Below is an illustration of yours and the given Design, please pay attention on the red markings on your design: :arrow_down: 

<table>
    <tr>
      <td>Your Design</td>
      <td>Given Design</td>
    </tr>
    <tr>
      <td>

![student](https://github.com/jlcarrascof/bookstore-cms/assets/43528594/2049cbc2-efdf-466a-987a-e171fbc4120d)


</td>
      <td>

![BigZep](https://github.com/obibaadoma/book-stores/assets/43528594/f3df91c1-0159-4b9d-ad3e-00d89a12e295)

</td>
    </tr>
  </table>  

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 14:51 UTC, jlcarrascof commented
Ohh yes, sir **@Alusp** 

The **dropdown in that box**. I'll fix it and I'll update the readme file, before merge. Thanks, buddy.

2023-08-26 15:20 UTC, Alusp commented
You are welcome @jlcarrascof, and always remember to use color codes given in your given requirements, it will make you a professional developer in the near future. The opacity for your category on the nav was given on the zeplin. Please consider using adding it as well. 🙂

2023-08-27 04:52 UTC, jlcarrascof commented
> You are welcome @jlcarrascof, and always remember to use color codes given in your given requirements, it will make you a professional developer in the near future. The opacity for your category on the nav was given on the zeplin. Please consider adding it as well. 🙂

As I told you before, my man .... I had an Electricity maintance in my neighboorhood today for about 4 hours and when the energy returned, the 220 power failed. They fixed the issue only two hours ago. 

I'll merge and then I'll open a new branch to work tomorrow morning in the updates.

For now, I left you a star in your pinned projects, brother **@Alusp** 

Thanks for your comprehension. 

Javier.-
Venezuela.

2023-08-27 04:52 UTC, merged